### ISSUE TITLE
Ruby's Array and ActiveSupport has many difficult methods.

### ISSUE THREAD

**Issue by tashirosota** [tashirosota/ex-r_enum#12]
It's a difficult implementation, so I'd be happy if someone could cut it out and implement it...
https://qiita.com/shshimamo/items/5a458ecc88e7c24d5112
Please create a PR for [here](https://github.com/tashirosota/ex-r_enum/pull/4)

**Comment by mnishiguchi** [comment]
I think we need to prioritize what we really want first. 

For example, I wonder if it is worth implementing `zip` and `transpose` since Elixir has `Enum.zip/2` which is different but similar enough to Ruby's.
I mean this library shines when it provides really useful functions Elixir does not offer currently so it would be ideal if we focus on delivering important ones quickly rather than copying all the Ruby methods.

I think your personal subjective judgement would be fine, like:
- which Ruby methods you think are more useful than others?
- how often / rarely you would use those methods?

**Comment by tashirosota** [comment]
@mnishiguchi 
> this library shines when it provides really useful functions Elixir does not offer currently

I thinks it's too. 

Also, I think that will shine this when Ruby engineers  when learning Elixir too, so I also want to secure all the functions as much as possible.

However, since time and physical strength are finite, I will do it patiently while watching the situation.

Also, I just like to work with someone, so I created this issue！

**Comment by mnishiguchi** [comment]
Oh I missed the list in `feature/list_ruby` branch! Awesome!

For those who wants to contribute, here is a list of Ruby array functions we want to implement.
https://github.com/tashirosota/ex-r_enum/blob/feature/list_ruby/lib/r_list/ruby.ex

**Comment by mnishiguchi** [comment]
We should skip implementing `bsearch` because Elixir's `List` is a linked list. `List.at/2` scans a list from the beginning, which prevents us from implementing efficient binary search.

https://apidock.com/ruby/v2_5_5/Array/bsearch

**Comment by mnishiguchi** [comment]
Some info
- Ruby Array prepend is the same as unshift.
- Ruby Array hash is just a hash function. Maybe we can skip it?
- Ruby Array pack is very complex. Probably we would want a separate module if we want to implement it. Maybe skip?
